" James .vimrc

" Disable Vi compatibility. (So the Vim improvements are active)
set nocompatible

" General Config
set number                      " Line numbers are good
set backspace=indent,eol,start  " Allow backspace in insert mode
set history=1000                " Store lots of :cmdline history
set showcmd                     " Show incomplete cmds down the bottom
set showmode                    " Show current mode down the bottom
set gcr=a:blinkon0              " Disable cursor blink
set autoread                    " Reload files changed outside vim
set hidden                      " Turn on hidden buffers
syntax on                       " Turn on syntax highlighting

" Turn Off Swap Files
set noswapfile
set nobackup
set writebackup     " Create backup of original file to delete after successful write

" Indentation
set autoindent      " Copies indentation from previous line
set smartindent     " Automatically inserts one extra level of indentation
set smarttab        " Inserts indentation according to 'shiftwidth'
set shiftwidth=2    " Number of spaces for each indentation
set softtabstop=2   " Number of spaces a tab has when editing
set tabstop=2       " Number of spaces a tab in a files counts for
set expandtab       " Tabs become spaces
set nowrap          " Don't wrap lines
set linebreak       " Wrap lines at convenient points

" Auto indent pasted text
nnoremap p p=`]<C-o>
nnoremap P P=`]<C-o>

" Scrolling
set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

" Search
set incsearch       " Find the next match as we type the search
set hlsearch        " Highlight searches by default
set ignorecase      " Ignore case when searching...
set smartcase       " ...unless we type a capital
