# zshenv - zsh version 5.3.1
# James Roberts

# General
export PATH="/usr/local/bin/:$PATH"
export PATH="/usr/local/opt/llvm/bin:$PATH"
export DOTHOME="${HOME}/.dotfiles"
export EDITOR="/usr/bin/vim"
export GPG_TTY=$(tty)

# Homebrew
export HOMEBREW_CASK_OPTS="--appdir=~/Applications --fontdir=/Library/Fonts"    # Set hombrew options...
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_EMOJI=1

# Python Virtual Environments
export WORKON_HOME=~/.virtualenvs
local venv=/usr/bin/python3 && [[ -f /etc/debian_version ]] || local venv=/usr/local/bin/python3
export VIRTUALENVWRAPPER_PYTHON=$venv
source /usr/local/bin/virtualenvwrapper.sh

# Ruby Virtual Environments
eval "$(rbenv init -)"
