# zshenv - zsh version 5.3.1
# James Roberts

# General
export DOTHOME="${HOME}/.dotfiles"
export EDITOR="/usr/bin/vim"

# Homebrew
export HOMEBREW_CASK_OPTS="--appdir=~/Applications --fontdir=/Library/Fonts" 	# Set hombrew options...
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_EMOJI=1

# Python Virtual Environments
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
source /usr/local/bin/virtualenvwrapper.sh
