# zsh version 5.3.1
# James Roberts

# Prompt
local user_name="%F{red}$(whoami)%f"
local host_name="%F{cyan}%m%f"
local path_string="%F{yellow}%1~%f"
local prompt_string="»"
local return_status="%(?:%{$fg[blue]%}$prompt_string:%{$fg[red]%}$prompt_string)"
PROMPT="$host_name $path_string $prompt_string "
[[ $(whoami) = "root" ]] && PROMPT="$user_name@$PROMPT"

RPROMPT="%T"

# Command history
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history
setopt EXTENDED_HISTORY

# Command Correction
setopt correct

# Autocompletion
fpath=(/usr/local/share/zsh-completions $fpath)

# Aliases
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

#  Git aliases
alias gs="git status"
alias ga="git add"
alias gaa="git add -A"
alias gcm="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias gl="git log --oneline"
alias gc="git checkout"
alias gf="git fetch"
alias gd="git diff"
alias gb="git branch"


# Easily access other config files
config() {
	case $1 in
		# Universal
		zsh) vim ~/.zshrc && source ~/.zshrc ;;
		zshenv) vim ~/.zshenv && source ~/.zshenv ;;
    vim) vim ~/.vim/vimrc ;;
		ssh) vim ~/.ssh/config ;;
		hosts) sudo vim /etc/hosts ;;
	  tmux) vim ~/.tmux.conf ;;
  esac
}


# OS specific commands
alias grep="grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}"
if [[ "$(uname)" == "Darwin" ]]; then # macOS/OSX/FreeBSD
	alias cask="brew cask"

	alias ls="ls -FG"
	alias ll="ls -lh"
	alias la="ll -a"
	alias wake_lambda="wakeonlan 70:8b:cd:58:61:1b"
else # Ubuntu/Debian and Arch
	alias ls="LC_COLLATE=C ls --color=auto -F"
	alias ll="ls -l"
	alias la="ll -a"
fi

if [[ -f /etc/arch-release ]]; then # Arch specific aliases
	# Essentials
	alias startx="ssh-agent startx"
	alias lock="$DOTHOME/scripts/lock.sh"

	# Administration
	alias pacman="sudo pacman"
	alias visudo="sudo visudo"

	# Misc
	alias set_wallpaper="feh --bg-fill"
	alias music="ncmpcpp"

	# Power
	alias poweroff="sudo systemctl poweroff"
	alias restart="sudo systemctl reboot"
	alias sleep="sudo systemctl suspend"
fi

# All below here is from the prezto completion module.
# Prezto is cool, but I only really wanted the completion from it.
# Group matches and describe.
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '%d'
zstyle ':completion:*:corrections' format ' %F{green}-- %d (errors: %e) --%f'
zstyle ':completion:*:descriptions' format ' %F{yellow}-- %d --%f'
zstyle ':completion:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'
zstyle ':completion:*:default' list-prompt '%S%M matches%s'
zstyle ':completion:*' format ' %F{yellow}-- %d --%f'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' verbose yes

# Fuzzy match mistyped completions.
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric

# Increase the number of errors based on the length of the typed word. But make
# sure to cap (at 7) the max-errors to avoid hanging.
zstyle -e ':completion:*:approximate:*' max-errors 'reply=($((($#PREFIX+$#SUFFIX)/3>7?7:($#PREFIX+$#SUFFIX)/3))numeric)'

# Don't complete unavailable commands.
zstyle ':completion:*:functions' ignored-patterns '(_*|pre(cmd|exec))'

# Array completion element sorting.
zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters

# Directories
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:cd:*' tag-order local-directories directory-stack path-directories
zstyle ':completion:*:*:cd:*:directory-stack' menu yes select
zstyle ':completion:*:-tilde-:*' group-order 'named-directories' 'path-directories' 'users' 'expand'
zstyle ':completion:*' squeeze-slashes true

# History
zstyle ':completion:*:history-words' stop yes
zstyle ':completion:*:history-words' remove-all-dups yes
zstyle ':completion:*:history-words' list false
zstyle ':completion:*:history-words' menu yes

# Environmental Variables
zstyle ':completion::*:(-command-|export):*' fake-parameters ${${${_comps[(I)-value-*]#*,}%%,*}:#-*-}

# Populate hostname completion.
zstyle -e ':completion:*:hosts' hosts 'reply=(
  ${=${=${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) 2>/dev/null)"}%%[#| ]*}//\]:[0-9]*/ }//,/ }//\[/ }
  ${=${(f)"$(cat /etc/hosts(|)(N) <<(ypcat hosts 2>/dev/null))"}%%\#*}
  ${=${${${${(@M)${(f)"$(cat ~/.ssh/config 2>/dev/null)"}:#Host *}#Host }:#*\**}:#*\?*}}
)'

# Don't complete uninteresting users...
zstyle ':completion:*:*:*:users' ignored-patterns \
  adm amanda apache avahi beaglidx bin cacti canna clamav daemon \
  dbus distcache dovecot fax ftp games gdm gkrellmd gopher \
  hacluster haldaemon halt hsqldb ident junkbust ldap lp mail \
  mailman mailnull mldonkey mysql nagios \
  named netdump news nfsnobody nobody nscd ntp nut nx openvpn \
  operator pcap postfix postgres privoxy pulse pvm quagga radvd \
  rpc rpcuser rpm shutdown squid sshd sync uucp vcsa xfs '_*'

# ... unless we really want to.
zstyle '*' single-ignored show

# Ignore multiple entries.
zstyle ':completion:*:(rm|kill|diff):*' ignore-line other
zstyle ':completion:*:rm:*' file-patterns '*:all-files'

# Man
zstyle ':completion:*:manuals' separate-sections true
zstyle ':completion:*:manuals.(^1*)' insert-sections true

autoload -U compinit
compinit
