# Set display to proper resolution (this is VM specific though...)
xrandr --output Virtual-1 --mode 1440x900 &

# Load Xresources
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# Run i3
exec i3
