# config: https://alacritty.org/config-alacritty.html

[window]
dimensions = { columns = 120, lines = 30 }
position = { x = 470, y = 300 }
opacity = 1.0
option_as_alt = "OnlyLeft"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 18
offset = { y = -3 }

[mouse]
hide_when_typing = true

