# config: https://alacritty.org/config-alacritty.html

[window]
opacity = 1.0
option_as_alt = "OnlyLeft"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 18
offset = { y = -3 }

[mouse]
hide_when_typing = true

