#! /bin/sh

# Start sxhkd
sxhkd &

# Define monitors
bspc monitor HDMI-0 -n 0 -d I II III
bspc monitor DVI-D-0 -n 1 -d IV V VI
bspc monitor DVI-D-1 -n 2 -d VII VIII IX X


# Mouse control
bspc config focus_follows_pointer true

# Default gaps
bspc config border_width         2
bspc config window_gap          12


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


